### ISSUE TITLE
Can't importe Pipeline in Azure Devops

### ISSUE THREAD

**Issue by lynxfg** [azlamsalam/sfpowerscripts#100]
Hello,

first of all i want to thank you for this plugin this this detailed documentation

I followed all the steps indicated on the documentation, but when importing the pipeline, I got this error:

> Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references to task called 'dea3a185-c3f5-44a8-841b-1e5044864778'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 3. *, job 'Job_1', step ''.) Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references to task called 'a81064ca-c1cc-4ebf-892f-6299fa36b151'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 5. *, job 'Job_1', step ''.) Error while creating release definition: Tasks with versions' Deploy force-di to $ (env.name): 3. * 'are not valid for deploy job' Agent job 'in stage ST.

Could you please help me move forward on the installation of this project?

Best regards

**Comment by jurgenvanwestreenen** [comment]
Hi there,

I'm getting the exact same error message(s).

Could you please advise on any next steps?

Regards,

Jurgen van Westreenen

**Comment by azlamsalam** [comment]
Thanks for raising the issue, I will be updating the sample pipeline shortly. The version numbers are mismatched whats happening in the release

**Comment by azlamsalam** [comment]
#43  This issue is related to this one and needs a fix

**Comment by azlamsalam** [comment]
Have updated the sample pipelines, looks all good , tested in a new org . Feel free to reach out using [slack](https://join.slack.com/t/sfpower/shared_invite/enQtNzcxMjE1MTg0ODIzLWFmNDRkY2NkOGE0NDkxMWVmZmQ1ODJhMGVhZTkzYjYzOWMyNWZiY2Y1YTlhZmU2NDAyMDVlODMyMjU1NWZmZjA)

Also ensure you have the latest version of the plugin installed, and all the permissions are in play.
