### ISSUE TITLE
task name typo?

### ISSUE THREAD

**Issue by staff0rd** [azlamsalam/sfpowerscripts#123]
[This task](https://github.com/azlamsalam/sfpowerscripts/blob/develop/BuildTasks/InstallSFDXCLITaskCurrent/task.json#L3) appears to have a typo in its name.  

### Current;
`sfpwowerscript-installsfdx-task`

### Proposed;
`sfpowerscript-installsfdx-task`

**Comment by staff0rd** [comment]
It seems a number (maybe most) have this typo, making me think it's not a typo.  If that's the case, then this one is the typo, as it already uses `sfpowerscript`; https://github.com/azlamsalam/sfpowerscripts/blob/develop/BuildTasks/DeploySourceToOrgTask/task.json#L3

**Comment by azlamsalam** [comment]
@staff0rd It was a typo , which I realised it quite late as was mostly using classic pipelines in the initial stage. Now It is very hard to fix, as it will break all existing implementation. So no easy way out..
