### ISSUE TITLE
Add buildSourceBranch to metadata file while package creation

### ISSUE THREAD

**Issue by ramesh-karanji** [azlamsalam/sfpowerscripts#133]
Can you please add buildSourceBranch to "sfpowerkit_artifact/metadata" file in "Create Unlock package build task" it will help to deploy package according to stream specific environments while downloading and extracting the details from metadata file.

**Comment by azlamsalam** [comment]
@ramesh-karanji  is the build source branch readily available as a variable in azure pipelines?

**Comment by ramesh-karanji** [comment]
@azlamsalam yes they are predefined variables
FYI - https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

**Comment by azlamsalam** [comment]
I don't think its necessary because of this, any specific usecases?

**Comment by ramesh-karanji** [comment]
i think this is not required anymore, good to close this issue.
