### ISSUE TITLE
Code Coverage for unlocked packages

### ISSUE THREAD

**Issue by azlam-abdulsalam** [azlamsalam/sfpowerscripts#14]
Provide an option for reporting code coverage for unlocked packages, add the output to the summary line and artefacts
https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_unlocked_pkg_code_coverage.htm
Also provide guidance on when to trigger based on the time difference between package creation with and without code coverage

**Comment by azlamsalam** [comment]
First version delivered with support for code coverage parameter when creation of unlocked package
