### ISSUE TITLE
Issue with DevOps demo generator template

### ISSUE THREAD

**Issue by infosatheesh2020** [azlamsalam/sfpowerscripts#24]
When I try to create demo generator project using https://raw.githubusercontent.com/azlamsalam/sfpowerscripts/master/SamplePipelines/sfpowerscripts-sample-pipelines.zip, it fails with below message:

Sorry, we ran into a issue

Diagnostic log:

Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called 'a81064ca-c1cc-4ebf-892f-6299fa36b151'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 3.*, job 'Job_1', step ''.)

**Comment by azlamsalam** [comment]
Thanks for raising the issue.. I will update it shortly, as some tasks are deprecated

**Comment by azlamsalam** [comment]
This is fixed in the latest zip file update.. Thanks again

**Comment by infosatheesh2020** [comment]
@azlamsalam I ran out of another error this time, diagnostics below:

Error while creating build definition: Invalid or missing service connection.
