### ISSUE TITLE
Issue with sample pipeline .zip

### ISSUE THREAD

**Issue by calvinle1** [azlamsalam/sfpowerscripts#28]
Error is thrown upon attempting to load sample pipeline .zip per instructions documented here: https://sfpowerscripts.com/gettingstarted/

Error message is:

_Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called 'd8950cd3-2bf4-4b50-bb75-b9358f741951'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 2.*, job 'Job_1', step ''.),A task is missing. The pipeline references a task called '5eb34b28-fdd4-4904-9a3e-d3ff63130f16'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 4.*, job 'Job_1', step ''.) Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called 'f67abc38-a5b8-4196-946e-ba81df4cd57c'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 1.*, job 'Job_1', step 'build'.),A task is missing. The pipeline references a task called '50de2eba-73bc-4cd6-82bc-89853925830c'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 4.*, job 'Job_1', step ''.) Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called 'd8950cd3-2bf4-4b50-bb75-b9358f741951'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 2.*, job 'Job_1', step ''.),A task is missing. The pipeline references a task called '5eb34b28-fdd4-4904-9a3e-d3ff63130f16'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 4.*, job 'Job_1', step ''.) Error while creating release definition: Tasks with versions 'Checkout from Git:4.*, Install SFDX:2.*, Authenticate $(env.name) using Credentials:4.*, Deploy force-di to $(env.name):2.*' are not valid for deploy job 'Agent job' in stage ST. Error while creating release definition: Tasks with versions 'Install SFDX:2.*, Authenticate HubOrg using Credentials:4.*, Authenticate $(env.name) using Credentials :4.*, Install a version of force-di to $(env.name) :4.*' are not valid for deploy job 'Agent job' in stage ST._

**Comment by azlamsalam** [comment]
Thanks for raising it, fixed!
