### ISSUE TITLE
Authenticate Sandbox

### ISSUE THREAD

**Issue by Majd-Soufan** [azlamsalam/sfpowerscripts#40]
I am trying to authenticate a sandbox using Authenticate an Org task, but it seems that it is only authenticating orgs with url https://login.salesforce.com and not https://test.salesforce.com for a Sandbox. Even though it is running the auth command with -r https://test.salesforce.com, but it is giving an error with the following log:

##[error]Command failed: npx sfdx force:auth:jwt:grant --clientid *** --jwtkeyfile *** --username autodeployer@dsg.com.canuat --setdefaultusername --setalias dsguat -r https://test.salesforce.com 

ERROR running force:auth:jwt:grant:  This org appears to have a problem with its OAuth configuration. 
Reason: invalid_grant - user hasn't approved this consumer 
username: autodeployer@dsg.com.canuat, 
clientId: ***, 
loginUrl: https://login.salesforce.com,      // Here it is not taking my AzureDevOps variable group URL
privateKey: ***

**Comment by azlamsalam** [comment]
Thanks for raising the issue @Majd-Soufan , can you verify whether your command run's locally..  fdx force:auth:jwt:grant --clientid *** --jwtkeyfile *** --username autodeployer@dsg.com.canuat --setdefaultusername --setalias dsguat -r https://test.salesforce.com

I am having a look

**Comment by azlamsalam** [comment]
No issue at our end,, can you check your connected app configuration?

**Comment by Majd-Soufan** [comment]
It was the connected app configuration. Thank you
