### ISSUE TITLE
Azure DevOps Plugin on marketplace not available for Azure Devops Server

### ISSUE THREAD

**Issue by nt5689** [azlamsalam/sfpowerscripts#62]
Currently the Azure Devops plugin in only available for **Azure Devops Services**, please make them also available for **Azure Devops Server 2019**.

**Comment by azlamsalam** [comment]
Thanks for raising the issue, I currently do not have a Azure DevOps Server 2019 to test the plugin. I will add this to the backlog and unblock it after testing

**Comment by azlamsalam** [comment]
@nt5689  I can make available a private version of the plugin enabled for Azure DevOps Server 2019, Will you be able to test it?

**Comment by nt5689** [comment]
@azlamsalam Yes, that would be great. we have an special environment to test it.

**Comment by nt5689** [comment]
Tasks tested and working on Azure Devops Server, pull request pending
