### ISSUE TITLE
When deploy source to org task fails, display the list of deployment errors

### ISSUE THREAD

**Issue by jhawk-kar** [azlamsalam/sfpowerscripts#73]
We use sfpower tasks to perform a pull request validation against the unlocked packaged.  When performing a deploy source to org task and a failure occurs, the error message 

`Exit with error code: 1`

is displayed on the PR status check.  It would be nice if the actual failures were presented to the user on the status check.  Not all of our development team has access to Azure DevOps, so we usually have to track down someone with access to report the errors back to them.  

![Screen Shot 2020-02-04 at 2 40 49 PM](https://user-images.githubusercontent.com/43937191/73780779-164e9200-475d-11ea-928b-c468d2a715f2.png)

**Comment by azlamsalam** [comment]
This looks like a good usecase and have been thinking for a while, but with different git hosting providers out there, would be little work on various api's
