### ISSUE TITLE
Analyze With PMD Task

### ISSUE THREAD

**Issue by azlam-abdulsalam** [azlamsalam/sfpowerscripts#8]
This task will be helpful to have do a static analysis of the apex code in the build/PR pipelines.  The task will do the following
1. Download PMD and set it up
2. Have a default ruleset along with the task, with an option to chose a custom one
3. Have a custom ruleset mode, that the user can override
4. Attach the output of PMD as a build artifact / formatted test result?
5.  Send it to github as a status?

**Comment by azlamsalam** [comment]
Delivered in 2.0.22
