### ISSUE TITLE
Analyze With PMD task fails to run on Windows Agent

### ISSUE THREAD

**Issue by azlam-abdulsalam** [azlamsalam/sfpowerscripts#85]
Analyze with PMD task fails to run on Windows Agent, Investigate also whether this relates to https://github.com/azlamsalam/sfpowerscripts/issues/82

**Comment by azlamsalam** [comment]
This taks fails as Java runtime is missing, works fine in vs hosted images

**Comment by mpaul1** [comment]
Is this the same bug:
##[section]Starting: Analyze force-app using PMD
==============================================================================
Task         : Run a static analysis of apex classes with PMD
Description  : This task is used to run a static analysis of the apex classes and triggers using PMD,This task is part of SFPowerscripts, Please ensure Install SFDX Task is used before utilizing this task
Version      : 4.3.10
Author       : azlam.abdulsalam
Help         : Utilizes PMD 6.18.0 to run a static analysis and attaches the output to the build artifact
==============================================================================
Test.. PMD
npx sfdx sfpowerkit:source:pmd -d  force-app -f  text --version=6.18.0 --loglevel INFO
INFO ‌ [2020-05-08 17:25:58.294 +0000] (sfpowerkit): ‌Found Java Home at null‌

PMD release 6.18.0

Now analyzing force-app

ERROR running sfpowerkit:source:pmd:  Path must be a string. Received null

##[error]Unhandled: Command failed: npx sfdx sfpowerkit:source:pmd -d  force-app -f  text --version=6.18.0 --loglevel INFO
ERROR running sfpowerkit:source:pmd:  Path must be a string. Received null

##[error]Exit with error code: 1
##[section]Finishing: Analyze force-app using PMD

**Comment by azlam-abdulsalam** [comment]
Yes think so, Can you check java is available in the agent you are using. I will open another issue to fix the error message @aly76
