### ISSUE TITLE
Deploy Source to Org unable to find Test Suite

### ISSUE THREAD

**Issue by jhawk-kar** [azlamsalam/sfpowerscripts#99]
When using the run test suite method for deploy source to org task, the task was unable to find the test suite in the files.  I used a checkout from Git task and then the source location variable from that task was passed to the deploy task.  The test suite was in the source files, but unable to be found by the task.

**Comment by azlamsalam** [comment]
@jhawk-kar  Can you confirm this behaviour is only in release pipeline?

**Comment by jhawk-kar** [comment]
We noticed it from running in a release pipeline, but I haven't used it in a build pipeline to be able to compare.  Our build pipelines run test suites through the run apex tests task and not the deploy task, so we can pull out the code coverage file.

**Comment by azlamsalam** [comment]
This is a bug with sfpowerkit, I have raised a PR which will fix it and then there are couple of minor tweaks based on it. Have raised a PR for the same as well. Will be release in 11.0
